### ISSUE TITLE
Pocket package name

### ISSUE THREAD

**Issue by buzinas** [jaredhanson/pocket#3]
Hi Jared!

I tried to send you an e-mail one month ago, but unfortunately didn't get an answer. Maybe my e-mail was marked as SPAM or something like that, not sure.

So, I'm opening this issue just to have a little chance to get your response.

I'm developing a tiny JS framework named PocketJS (I already have ~30% of the development done, bought the domain name etc etc), and I was willing to know if there is any possibility of you transfering this package name for me. I would really appreciate that.

Thanks in advance, and let me know if you need any other information, please.

**Comment by jaredhanson** [comment]
Sorry, no.
